### ISSUE TITLE
Any more specific place where you add this?

### ISSUE THREAD

**Issue by fleexcl** [Nathan-FiveM/qb-fiveems#1]
Bones.Options['bonnet'] = {
		["Seating"] = {
			type = "client",
			event = "qb-fivemems:client:StretcherSeatMenu",
			icon = "fas fa-ambulance",
			label = "Stretcher Seating",
			distance = 2.5
		},
		["Stretcher_Menu"] = {
			type = "client",
			event = "qb-fivemems:client:StretcherMenu",
			icon = "fas fa-ambulance",
			label = "Stretcher Menu",
			job = "ambulance",
			distance = 2.5
		},
		["EMS"] = {
			type = "client",
			event = "qb-fivemems:client:AmbulanceMenu",
			icon = "fas fa-ambulance",
			label = "EMS Menu",
			job = "ambulance",
			distance = 2.5
		},
		["Toggle_Hood"] = {
			icon = "fa-duotone fa-engine",
			label = "Toggle Hood",
			action = function(entity)
				ToggleDoor(entity, 4)
			end,
			distance = 2.5
		},
	}

**Comment by jayyy299** [comment]
Have you found out where to place it?
